import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfReportService {
  static Future<void> generateExecutiveReport({
    required int rpm,
    required double coolantTemp,
    required bool isMasterActive,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(24),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Header(
                  level: 0,
                  child: pw.Text('SentriX Core - Executive Diagnostic Report',
                      style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
                ),
                pw.SizedBox(height: 10),
                pw.Text('System Status: ${isMasterActive ? "MASTER ACTIVE" : "SAFE MODE (BASIC)"}'),
                pw.Divider(),
                pw.SizedBox(height: 15),
                pw.Text('OBD-II / CAN-Bus Live Diagnostics:', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                pw.Bullet(text: 'Engine Speed: $rpm RPM'),
                pw.Bullet(text: 'Coolant Temperature: $coolantTemp °C'),
                pw.Bullet(text: 'Hardware Fingerprint: 4b83c6bc6379df6f65e'),
                pw.SizedBox(height: 20),
                pw.Text('Generated by SentriX Core Security & Analytics Engine', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }
}
